export const EVENTS = {
  ZONE_UPDATE: "ZONE_UPDATE",

  INSTALLATION_STATE: "INSTALLATION_STATE",

  DWELL_PROGRESS: "DWELL_PROGRESS",

  SELECTION_CONFIRMED: "SELECTION_CONFIRMED",
} as const;

export type Zone = "CENTER" | "RED" | "BLUE" | "GREEN" | "YELLOW" | "NONE";
